### ISSUE TITLE
Document variances from default or strongly-held opinions

### ISSUE THREAD

**Issue by kevin-j-m** [TheGnarCo/gnar-style#11]
This repo should include a wiki, or a markdown file (preferable, so we can make changes along with other changes) that details whatever opinions we hold that require explanation.

This could be things that are enforced by rubocop by default, but that we want to highlight, items we've modified from the default rubocop settings to justify the opinion, or items that aren't caught by an automated system that we still want to draw attention to as house style.

**Comment by alxjrvs** [comment]
Gnar Style has been [deprecated](https://github.com/TheGnarCo/gnar-style/pull/62).
