### ISSUE TITLE
Explain contribution process

### ISSUE THREAD

**Issue by kevin-j-m** [TheGnarCo/gnar-style#12]
While the README does have a `Contributing` section, we should be more descriptive in there for exactly what we require in any changes to the repo. For suggested style changes, this could include:

* The change itself
* A detailed commit message explaining the change
* An update to the Changelog
* An update to our style preferences document, explained in #11

**Comment by alxjrvs** [comment]
Gnar Style has been [deprecated](https://github.com/TheGnarCo/gnar-style/pull/62).
