### ISSUE TITLE
Configure Pending cops from 0.80

### ISSUE THREAD

**Issue by kevin-j-m** [TheGnarCo/gnar-style#48]
This repo should take a stance on how each of these should be set, and release a new version where 0.80 of rubocop is the minimum along with these being set.

```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Style/HashEachMethods (0.80)
 - Style/HashTransformKeys (0.80)
 - Style/HashTransformValues (0.80)
For more information: https://docs.rubocop.org/en/latest/versioning/
```

**Comment by danfrenette** [comment]
Just to aggregate everything together:


[Style/HashEachMethods](https://rubocop.readthedocs.io/en/latest/cops_style/#stylehasheachmethods)

```ruby
# bad
hash.keys.each { |k| p k }
hash.values.each { |v| p v }

# good
hash.each_key { |k| p k }
hash.each_value { |v| p v }
```
 

[Style/HashTransformKeys
](https://rubocop.readthedocs.io/en/latest/cops_style/#stylehashtransformkeys)
```ruby
# bad
{a: 1, b: 2}.each_with_object({}) { |(k, v), h| h[foo(k)] = v }
{a: 1, b: 2}.map { |k, v| [k.to_s, v] }

# good
{a: 1, b: 2}.transform_keys { |k| foo(k) }
{a: 1, b: 2}.transform_keys { |k| k.to_s }
```


[Style/HashTransformValues](https://rubocop.readthedocs.io/en/latest/cops_style/#stylehashtransformvalues)

```ruby
# bad
{a: 1, b: 2}.each_with_object({}) { |(k, v), h| h[k] = foo(v) }
{a: 1, b: 2}.map { |k, v| [k, v * v] }

# good
{a: 1, b: 2}.transform_values { |v| foo(v) }
{a: 1, b: 2}.transform_values { |v| v * v }
```

**Comment by danfrenette** [comment]
I'm personally a fan of these method provided by Rails, I think they make the code considerably more readable and think standardizing on them would benefit any codebase.

That said, I'm not aware of (nor have I ever even considered) technical limitations/drawbacks of them, so please enlighten me if you know of any!

**Comment by kevin-j-m** [comment]
> technical limitations/drawbacks

I believe:
`transform_keys` was introduced in ruby 2.5
`transform_values` was introduced in ruby 2.4

So, you'd need to be using at least 2.5 to be able to take all the suggestions here. I don't think rubocop would break if you were using an earlier version, but it'd be suggesting something you couldn't do.

**Comment by danfrenette** [comment]
FWIW Rails added these methods in early versions of Rails 4. Looking at API Dock, it looks like `transform_keys` and `transform_values` were added in Rails 4.0.2 and 4.2.1 respectively. 

Ruby 2.5 is about 2 years old, while Rails 4.2 is considerably older, so I think we're safe with the projects Gnar is currently working on (might be different for anyone else using this gem though, but then I guess that's what this thread is for).

**Comment by kevin-j-m** [comment]
I'd prefer to have this in our `rubocop.yml` than our `rubocop-rails.yml` configuration, which is why I'm considering when these were introduced into ruby itself.

That said, I'm not making an argument that we shouldn't implement this (we __have__ to address it directly if we want to use rubocop >= 0.80.0 and not get warnings), but you asked for limitations...

**Comment by danfrenette** [comment]
Agreed! Plus we'd want to use this for gems too. I just thought I'd mention it as you _could_ still do these things in Rails without Ruby 2.5 if we were to enforce it.

**Comment by zfletch** [comment]
Unrelated to the cops themselves but related to the configuration: I think it would be a good idea in `rubocop.yml` to separate these cops from the other cops and to leave a comment about them.

When Rubocop enables these cops by default in the next major release, they can then be removed. Otherwise it will become difficult to tell pending cops from cops intentionally configured differently from the default.

**Comment by danfrenette** [comment]
> it will become difficult to tell pending cops from cops intentionally configured differently from the default.

Great suggestion! This will save us a ton of work (and pain).

**Comment by alxjrvs** [comment]
Gnar Style has been [deprecated](https://github.com/TheGnarCo/gnar-style/pull/62).
